# Generated by Django 6.1.1 on 2026-09-18 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('partnership_type', models.CharField(choices=[('strategic', 'Strategic Partnership'), ('technical', 'Technical Collaboration'), ('distribution', 'Distribution Partnership'), ('research', 'Research Collaboration'), ('investment', 'Investment Partnership'), ('other', 'Other')], default='strategic', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('startup_type', models.CharField(choices=[('public', 'Public'), ('individual', 'Individual')], default='public', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='startups/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='startups/covers/')),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('incubation_start', models.DateField(blank=True, null=True)),
                ('incubation_end', models.DateField(blank=True, null=True)),
                ('year_incubated', models.PositiveIntegerField(blank=True, null=True)),
                ('contract_status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('profile_completion', models.PositiveIntegerField(default=0, help_text='Percentage of profile completed')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('consulting', 'Consulting'), ('financial', 'Financial Services'), ('marketing', 'Marketing'), ('logistics', 'Logistics'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('agriculture', 'Agriculture'), ('other', 'Other')], default='other', max_length=20)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='staff.startup')),
            ],
        ),
        migrations.CreateModel(
            name='PitchDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='pitch_decks/')),
                ('presentation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_decks', to='staff.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('opportunity_type', models.CharField(choices=[('funding', 'Funding'), ('mentorship', 'Mentorship'), ('partnership', 'Partnership'), ('market_access', 'Market Access'), ('acceleration', 'Acceleration')], default='funding', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], default='open', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='staff.startup')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('unit', models.CharField(blank=True, help_text='e.g. users, revenue, %', max_length=50)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='staff.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Investor or fund name', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funding_type', models.CharField(choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('grant', 'Grant'), ('debt', 'Debt'), ('other', 'Other')], default='seed', max_length=20)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('committed', 'Committed'), ('received', 'Received'), ('pending', 'Pending'), ('declined', 'Declined')], default='committed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='staff.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('co_founder', 'Co-Founder')], default='founder', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='founders/avatars/')),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='staff.startup')),
            ],
        ),
    ]
