# Generated by Django 5.1.4 on 2026-09-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_registrationrate_loginnotification_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='contract_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20),
        ),
    ]
