# Generated by Django 5.1.4 on 2026-09-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_investor_mentor_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='startup',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='startup',
            name='source',
            field=models.CharField(default='DTBi', max_length=255),
        ),
    ]
