# Generated by Django 6.1.1 on 2026-09-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_startup_contact_email_startup_phone_startup_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='directory_visible',
            field=models.BooleanField(default=True),
        ),
    ]
