# Generated by Django 5.2.17 on 2026-09-24 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_startup_directory_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='funding',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundings', to='staff.investor'),
        ),
        migrations.CreateModel(
            name='DataImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('startup', 'Startups'), ('mentor', 'Mentors'), ('investor', 'Investors')], max_length=20)),
                ('file', models.FileField(upload_to='imports/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('preview', 'Ready to import'), ('completed', 'Completed'), ('failed', 'Failed')], default='preview', max_length=20)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('row_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('topics', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='staff.mentor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_engagements', to='staff.startup')),
            ],
            options={
                'ordering': ['-date', 'mentor__name'],
                'indexes': [models.Index(fields=['date'], name='staff_mento_date_dce71b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('startup', 'Startup'), ('mentor', 'Mentor'), ('investor', 'Investor')], max_length=20)),
                ('object_key', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('session_key', models.CharField(max_length=40)),
                ('visit_date', models.DateField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_page_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['page_type', 'visited_at'], name='staff_pagev_page_ty_c700e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('page_type', 'object_key', 'session_key', 'visit_date'), name='uniq_daily_entity_page_visit')],
            },
        ),
        migrations.CreateModel(
            name='StartupStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], max_length=20)),
                ('contract_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='staff.startup')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['recorded_at', 'status'], name='staff_start_recorde_57ec59_idx')],
            },
        ),
    ]
