# Generated by Django 5.2.17 on 2026-09-24 20:57

import staff.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_funding_currency_funding_investor_dataimportbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimportbatch',
            name='file',
            field=models.FileField(storage=staff.storage.PrivateImportStorage(), upload_to='imports/%Y/%m/'),
        ),
    ]
