# Generated by Django 5.1.4 on 2026-09-24 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_dataimportbatch_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_partnerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnership',
            name='expected_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='proposed_contribution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='related_startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_requests', to='staff.startup'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='startup_benefit',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='partnership_type',
            field=models.CharField(choices=[('strategic', 'Strategic Partnership'), ('technical', 'Technical Collaboration'), ('distribution', 'Distribution Partnership'), ('research', 'Research Collaboration'), ('investment', 'Investment Partnership'), ('funding', 'Funding and Co-investment'), ('mentorship', 'Mentorship and Capacity Building'), ('market_access', 'Market Access and Procurement'), ('ecosystem_support', 'Ecosystem Services and Infrastructure'), ('other', 'Other')], default='strategic', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PartnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_status_changes', to=settings.AUTH_USER_MODEL)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='staff.partnership')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
