# Generated by Django 5.2.17 on 2026-09-24 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_mentorengagement_meeting_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorEngagementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], max_length=20)),
                ('old_date', models.DateField(blank=True, null=True)),
                ('new_date', models.DateField()),
                ('old_start_time', models.TimeField(blank=True, null=True)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_session_changes', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='staff.mentorengagement')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['changed_at', 'new_status'], name='staff_mento_changed_5f024f_idx')],
            },
        ),
    ]
