# Generated by Django 5.2.17 on 2026-09-24 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_mentorengagementhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('current_stage', models.CharField(choices=[('buni_community', 'BUNI community / outreach'), ('buni_internship', 'BUNI internship'), ('buni_mentoring', 'BUNI mentoring'), ('buni_preincubation', 'BUNI pre-incubation'), ('dtbi_preincubation', 'DTBi pre-incubation'), ('dtbi_incubation', 'DTBi incubation'), ('dtbi_growth', 'DTBi growth'), ('alumni', 'Alumni / post-programme follow-up')], default='buni_community', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('exited', 'Exited')], default='active', max_length=20)),
                ('cohort', models.CharField(blank=True, max_length=120)),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal programme notes. Do not enter sensitive personal data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_participant_journeys', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_journeys', to='staff.startup')),
            ],
            options={
                'ordering': ['-updated_at', 'participant_name'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_participant_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_follow_ups', to='staff.mentor')),
                ('mentor_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_follow_ups', to='staff.mentorengagement')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='staff.participantjourney')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantJourneyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_stage', models.CharField(blank=True, max_length=30)),
                ('new_stage', models.CharField(choices=[('buni_community', 'BUNI community / outreach'), ('buni_internship', 'BUNI internship'), ('buni_mentoring', 'BUNI mentoring'), ('buni_preincubation', 'BUNI pre-incubation'), ('dtbi_preincubation', 'DTBi pre-incubation'), ('dtbi_incubation', 'DTBi incubation'), ('dtbi_growth', 'DTBi growth'), ('alumni', 'Alumni / post-programme follow-up')], max_length=30)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('exited', 'Exited')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_journey_changes', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='staff.participantjourney')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('full_time_jobs', models.PositiveIntegerField(default=0)),
                ('part_time_jobs', models.PositiveIntegerField(default=0)),
                ('monthly_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('revenue_currency', models.CharField(default='TZS', max_length=3)),
                ('customers_or_users', models.PositiveIntegerField(blank=True, null=True)),
                ('milestone', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='staff.participantjourney')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_participant_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(choices=[('training', 'Training / capacity building'), ('fabrication_lab', 'Fabrication lab / prototyping'), ('business_advisory', 'Business advisory'), ('market_access', 'Market access / procurement'), ('finance_access', 'Finance / investor readiness'), ('hub_linkage', 'Hub / ecosystem linkage'), ('other', 'Other support')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('delivered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('provider', models.CharField(blank=True, help_text='Team, partner, trainer, or facility', max_length=255)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_deliveries', to='staff.participantjourney')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_participant_support', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-delivered_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='participantjourney',
            index=models.Index(fields=['current_stage', 'status'], name='staff_parti_current_acf5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='participantjourney',
            index=models.Index(fields=['cohort'], name='staff_parti_cohort_dff42b_idx'),
        ),
        migrations.AddIndex(
            model_name='participantoutcome',
            index=models.Index(fields=['recorded_on'], name='staff_parti_recorde_785208_idx'),
        ),
    ]
